language: ruby
rvm:
- 2.5.3
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rubocop -P
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  run: rake db:migrate
  app: team-avengers
  api_key:
    secure: PYF1QwoBdr915GtaTNOt0RyLWTvnzc6ml7V+ojuquz9obaaC+sZvRAUm2RKIGKRaV5OAukyydOhVmKkCe7oF+XJW2WWYXsPWQnGCY3eDmOMG63paceC4L3f+NEEKAG6/Qj3P59keZqvYK1qmAkShYuJIN8c+rR/B1umoewWzeT6JqhnRyMRsg2SM5bBgDwyoOpS0hYGvXwwVsMyozt+8Vk9cInNMyvT9Fl5ujeNbXRDbg0eIwHCNyw+U01ObNI9j1ZLH/DzL6oXNkZscmTRZwSI5dPxNF9X5x0YW9y4Q3G15YN8tIov2T09QCBS0JLVJUHr9V6VAtlTO+qb9V8KH6hnqC1KPHEusy8iX11K0+06l8gQTT7CIrXDeu7TBwnjKISUTLA4+AW1uxte6+pzDvuCdUu/2FqGF9m3IwbrvpnCpj87tJFPr8U4d7f2GRlgwBYjzL5fjA6H4BlC2tyr7swQrYHhY+GzuPnBm9+cowtgKuy7AHL7AztzhT58d1HsRKFgVUY3hFdaw1ICxybuydFMNbo9rz+vSIRecrjwLxda/TxuaLkr9z6Tc6II81mLYZ1LIxvkkLan+fLgWPEpet6DYWG6inSzGraI3B003uVk32+fOQzxIfXnwxlfMmlpbHSnz+pxXmvIdn0x14ookxsWyrJZifdr4+WJXBqvgYQ4=
  on:
    repo: netguru-code-college/krk-18-avengers
notifications:
  slack:
    secure: GP5D2HkKwX+1aArdqS7QBuUcK+XjDzqMIE7oi8qQB1N+Ki+TAc4QNvpROAebTRN5i/1tZlKtttJiRGt+/k2eKVsj462vf795TK7bIx7mNSZi9nTXnH67gBIqXwd5t8fuDDbijSvSFyTYKWACZQ/zqZoZuxx+8pH9L3pzyBMWEGnhGQb9DVdC71MzWYzDh29wSRmMkDE5ImqCoHbE488MXETdeuUPHWOUObfZxijt/6RR7G8YhimqcmRUw5cyMKcRmxN3QIDxZz+Aw0NW4eLvkgQXgK7qiGVTbKEijcwCqmY076pxMinsobXzE8k5aheni/TE089sibs1dOXvKYvyF8lm4+XcE7WGjdwlC0Ls4wfY9CxVBD0WA20Z2y+goXkrBsS8+ldQWLntXZ0zUFvlfSpxKpH+jPrdlWondAZcSMVn352CBAzb+BYDW8f4gBMMExhjU4fIPrhuT26YA4zyi4fJjExIUeUDdpfNKfgUTZ/qz/oNRvmS1b8UZfSgUFPjjrbEGKGe0hQ54zNKG8a/UpsksTiSi17Yd+566XxMXCStXrACQ32PRIFs2pEUXex+PUnCTgyfbM8n9Eg2S6NI9N5kW3fISVuGxfibO36uoyrk9v+8fyOiUfV5+WYPCKDu0I9NRNRi0Uuo6JLOo+6aGrVkdH6f9oRa7GFqjUPe8Wc=
